### ISSUE TITLE
Is this project still under maintained ?

### ISSUE THREAD

**Issue by snguyenthanh** [eltrino/diamantedesk-application#137]
Hi, may I ask if this project is still maintained ? I have not seen updates from the maintainers for a while and the last commit was almost 1 year ago.

**Comment by vikagudym** [comment]
> Hi, may I ask if this project is still maintained ? I have not seen updates from the maintainers for a while and the last commit was almost 1 year ago.

Hi! We are updating our product. But all new updates are not in the master. In the near future, a new version of the product will be available. Please tell me, what updates and improvements are you interested in?

**Comment by snguyenthanh** [comment]
Thanks for your reply. I'm interested in the product for its ticket statistics and planning to use it for my small team.
As there are some unanswered issues in the repo, I was concerned if the repo is still being actively developed to be used on production.
