### ISSUE TITLE
Allow direct message removing in ImapMessageProvider

### ISSUE THREAD

**Issue by quazardous** [eltrino/diamantedesk-application#15]
Some IMAP server do not allow to copy message.
so the ZF Imap::moveMessage() does not work (it does a copy then a remove)

You should provide some kind of option to directly remove the processed messages.

    src/Diamante/EmailProcessingBundle/Infrastructure/Message/Zend/ImapMessageProvider.php

**Comment by kstupak** [comment]
Thank you @quazardous 
We'll create an improvement for this issue.

**Comment by odi-um** [comment]
Solved in 50a5380ead3ef570a660f2f0b5de096f11ff67c9
