### ISSUE TITLE
missing require in composer.json for bundle generation

### ISSUE THREAD

**Issue by quazardous** [eltrino/diamantedesk-application#17]
missing "sensio/generator-bundle": "^2.3" in composer.json 

http://www.orocrm.com/documentation/index/current/cookbook/how-to-create-new-bundle#enable-bundle

**Comment by kstupak** [comment]
Hi @quazardous 
Thank you for your insights, we really appreciate your contribution effort. 

DiamanteDesk is built with Oro Platform and we never did require sensio/generator-bundle as it was never required in original oro/platform-application repository.

**Comment by quazardous** [comment]
ok,
fyi _profiler is also missing from whitelist.xml for proper dev...
