### ISSUE TITLE
Can not download translations

### ISSUE THREAD

**Issue by langj** [eltrino/diamantedesk-application#2]
When I trie to Download a Translation in the Language settings, I get the Error:

    Could not download translations, error: unknown

The js makes a request to `http://diamantedesk.local/translation/download/de_DE` which fails with a 403.

**Comment by northdakota** [comment]
Hi @langj, Thanks for report. we found the problem and fix it.
Could you update your application by next command
```bash
composer update
``` 
Also, before running, please make sure that your application switched to branch 1.0

**Comment by langj** [comment]
Nice, thank you. It works now.
