### ISSUE TITLE
Branch E-mail configuration

### ISSUE THREAD

**Issue by przestrzal** [eltrino/diamantedesk-application#20]
In my Diamante Desk there is no option to set branche e-mail configuration like this from documentation:

![image](https://cloud.githubusercontent.com/assets/17744192/13654717/2278e020-e65a-11e5-85b4-ddacdac8f0dd.png)

In my DD it looks like:

![image](https://cloud.githubusercontent.com/assets/17744192/13654730/3d93ef08-e65a-11e5-9325-8eabec291fa9.png)

Maybe i've missed some specific configuration, which enable this possibility?

**Comment by northdakota** [comment]
Hi Przestrzal, 
At this moment, we made changes to the behaviour of this functionality, and temporary remove it from master branch.

If you want to use this functionality at the moment, please reinstall application with branch 1.0

Thanks!

**Comment by przestrzal** [comment]
Hmmm, so is there any possibility to redistribute e-mails with different addressee to different branches without it?

Or should i downgrade to 1.0?

**Comment by northdakota** [comment]
Yes, at this moment I can propose few solutions :

1. downgrade to 1.0 (recommended)
2. Do checkout to commit 740ef8e4d16b11c0ee9f9c56e71901a3be7da8e3
3. Wait for the next release, where this functionality will be "restored"

Thanks!
