### ISSUE TITLE
PHP Fatal error: Uncaught InvalidArgumentException: Unknown compiler 

### ISSUE THREAD

**Issue by stephanvierkant** [eltrino/diamantedesk-application#32]
I'm trying to install diamantedesk (master) with `oro/platform` master, I got this error message:

> Fatal error: Uncaught RuntimeException: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Unknown compiler pass "Oro\Bundle\PlatformBundle\DependencyInjection\Compiler\UpdateDoctrineEventHandlersPass". in /home/stephan/scrn/edesk/vendor/oro/platform/src/Oro/Bundle/EntityExtendBundle/OroEntityExtendBundle.php on line 131
> 
> RuntimeException: PHP Fatal error:  Uncaught Symfony\Component\DependencyInjection\Exception\InvalidArgumentException: Unknown compiler pass "Oro\Bundle\PlatformBundle\DependencyInjection\Compiler\UpdateDoctrineEventHandlersPass". in /home/stephan/scrn/edesk/vendor/oro/platform/src/Oro/Component/DependencyInjection/ExtendedContainerBuilder.php:86
> 

Tested on PHP 7.0.7 and 5.6.22. When I try to install `oro/platform` as a separate project, it works.

**Comment by chris-freedom** [comment]
@stephanvierkant DiamanteDesk don't support current master branch of Oro Platform. Try to install DiamanteDesk 2.0.1 version.

**Comment by stephanvierkant** [comment]
Unfortunately that branch doesn't support PHP 7 right now. I was a bit surprised by their update policy: https://github.com/orocrm/platform/issues/545

What are your plans with updating to the latest stable version of oro/platform?

**Comment by odi-um** [comment]
@stephanvierkant explanation could be found in #33
