### ISSUE TITLE
HTTP Action

### ISSUE THREAD

**Issue by noahmehl** [eltrino/diamantedesk-application#35]
We are looking into this project and are really impressed.  However, it seems like the only action for a rule match is to email?  We were hoping to be able to do HTTP GET/POST actions for XML/JSON.  Is this a feature already or is it a planned feature?

**Comment by chris-freedom** [comment]
@noahmehl there are other ways to create tickets. 

The first way is to create through diamante portal, more details you can read here http://docs.diamantedesk.com/en/latest/user-guide/channels/portal.html

The second way is to use restful api with WSSE authentication. It supports json and xml format. 
Api documentation and sandbox you can find here http://your-domain.local/app_dev.php/api/doc

For example, if you want to create new ticket, first of all you need to genarate credential for user.
If it orocrm user, run in your project root following command:

`php app/console oro:wsse:generate-header api_key`

Output data insert in request headers using this url http://your-domain.local/api/rest/latest/desk/tickets.json and following body:

```json
{
  "attachments": [],
  "branch": 1,
  "comments": [],
  "created_at": "2017-01-03T19:22:41+0000",
  "description": "Test Description",
  "id": 34,
  "key": "BRANCHB-14",
  "priority": "medium",
  "reporter": "oro_1",
  "reporter_email": "akolomiec1989@gmail.com",
  "source": "phone",
  "status": "open",
  "subject": "Test Ticket from API",
  "unique_id": {
    "id": "d8f621778f73be58d7ce5d310f42f693"
  },
  "watcher_list": []
}
```

Api request example using postman

![2017-01-03 21-22-46](https://cloud.githubusercontent.com/assets/6242227/21621307/18677ec8-d201-11e6-9cc3-1ad5fe792d29.png)

More information about restful api you can read here http://docs.diamantedesk.com/en/latest/developer-guide/restful-api-guide.html

**Comment by noahmehl** [comment]
Chris, thanks for the reply.  We have a specific need whereby DiamanteDesk will post to an HTTP endpoint when ticket actions are met.  For instance, we have a partner ticketing system that we want to notify when we assign the ticket to them for instance.  Make sense?

**Comment by chris-freedom** [comment]
@noahmehl unfortunately DiamanteDesk does not support this feature. But you can add support by extending rule action. For instance, look at `src/Diamante/AutomationBundle/Automation/Action/Email/NotifyByEmailAction.php` class.

**Comment by noahmehl** [comment]
@chris-freedom that's what we thought, just making sure your team isn't adding this in the near future so we don't duplicate effort.
