### ISSUE TITLE
I don't have Email Configuration when I want create branch... ? 

### ISSUE THREAD

**Issue by xseth** [eltrino/diamantedesk-application#36]
I don't know why I fallow the documentation but I don't have Email Configuration in branch section. 

Thank for your reply
great job

**Comment by odi-um** [comment]
Hi @xseth, changes for documentation currently in progress. It has some outdated information. Email configuration have been moved to Rules. It was made to be more flexible for configuration. 

Please refer to this section of the docs http://docs.diamantedesk.com/en/latest/user-guide/rules.html

Thank you.

**Comment by xseth** [comment]
Ok thank you for your reply. 

I tryed to create few Event Triggered but It would seem that the rules do not work..  I don't know why.. 
I tryed simply rules: If ticket property updated reporter email is equal to "customer@mail.com"
Move to branch Web

When I create ticket with this reporter email adresse I have ticket created but is not moved to branch Web... :(

**Comment by odi-um** [comment]
We have just found that documentation is missing critical part regarding this situation. Forgot to add cron configuration section. You will need to add such command into your crontab (or to something else if you use not unix-like system)

```
*/1 * * * * php app/console diamante:cron > dev/null
```

also you can add another command for email processing to the cron. so it will automatically fetch everything.

**Comment by xseth** [comment]
Thank you its work fine now ! ;) Great job
