### ISSUE TITLE
Login not working after install

### ISSUE THREAD

**Issue by romeugodoi** [eltrino/diamantedesk-application#38]
Hi, First thank you for this project!! 👏

After finished install (successful) of this project I can't login with my user and password that I set on setup process.

Have someone this problem too?
What should I do to fix this problem? 

Thanks.

**Comment by romeugodoi** [comment]
I've installed from branch 2.0.

**Comment by odi-um** [comment]
hi @romeugodoi, could you provide more details ? 
where you try to login, main for admin users or on portal (for customers)? 
do you have any errors in logs (under app/logs) ? Could you post those files ?

Thank you.

**Comment by romeugodoi** [comment]
Hi @odi-um, I found out that this problem was occurring cos I was using a vagrant VM, and the ORO platform has a problem specially with session files to execute into NFS file system. I think it's not totally an ORO problem, but I've not seen another solution about this problem by them. 

So had to move to another server with no NFS file system to try this project.

Another guy had this problem too how can you see: https://www.orocrm.com/forums/topic/login-issue-redirect/#post-17738

**Comment by romeugodoi** [comment]
@odi-um .. would be interesting to add this info to README to avoid another people to spend so much time with this issue like me.

**Comment by odi-um** [comment]
@romeugodoi we have added faq section to docs
