### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by edfxp** [eltrino/diamantedesk-application#40]
Hi, 

I have successfully installed DiamanteDesk at my localhost,
but i have an issue that there's no notification

What should i setup, i tried to setup under parameters.yml, parameters.yml.dist, in the channel tab and tried to run got this result:
> app/console oro:cron:diamante:emailprocessing:general
> Start General Email Processing
> General Email Processing Done

 i still no notification, please help

Thanks

**Comment by northdakota** [comment]
Hi edfxp,
following command 
`app/console oro:cron:diamante:emailprocessing:general`
used for receiving messages from mail box to DiamanteDesk.

As i understood you want to enable notifications from DiamanteDesk to email boxes.
In this case you should run following command:
`app/console diamante:cron`

Also you should check that your email box has SMTP support

If you have more questions, please ask
Thanks!

**Comment by northdakota** [comment]
Also you can add this command to the system cronjob, 
`app/console diamante:cron`
So as result you will not need to run it manually

**Comment by edfxp** [comment]
Thanks
