### ISSUE TITLE
Branch new ticket or update comment...

### ISSUE THREAD

**Issue by xseth** [eltrino/diamantedesk-application#47]
Hi,

I make a rule for create new ticket with email contain a domain name to a branch it's work perfectly but the notification come with the wrong ID DB-XX (default id) but in my ticket I can see the good ID branch. And same problem if the reporter comment from mail a ticket already created this action create a new ticket but the ticket already created and the notification is send with the wrond id DB...

Thanks

**Comment by chris-freedom** [comment]
@xseth can you add sceenshots of rules that don't work?

**Comment by chris-freedom** [comment]
@xseth we reproduced a bug with different tickets key in the email notifications and fix it in the near future. About the creation of a new ticket instead of updating the existing one, can you tell me what email client and server are you using?

**Comment by xseth** [comment]
@chris-freedom Thanks for your reply.
I create a ticket from your desk application https://help.eltrino.com with screenshot...
