### ISSUE TITLE
Keep Getting This Error When I Did Php app/check.php

### ISSUE THREAD

**Issue by izakhearn** [eltrino/diamantedesk-application#65]
# php app/check.php
PHP Fatal error:  Uncaught Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException: The Symfony\Component\Intl\Collator\Collator::__construct() method's argument $locale value 'fr_FR' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities. in C:\xampp\htdocs\vendor\symfony\symfony\src\Symfony\Component\Intl\Collator\Collator.php:80
Stack trace:
#0 C:\xampp\htdocs\app\SymfonyRequirements.php(619): Symfony\Component\Intl\Collator\Collator->__construct('fr_FR')
#1 C:\xampp\htdocs\app\OroRequirements.php(25): SymfonyRequirements->__construct()
#2 C:\xampp\htdocs\app\DiamanteDeskRequirements.php(16): OroRequirements->__construct()
#3 C:\xampp\htdocs\app\check.php(6): DiamanteDeskRequirements->__construct()
#4 {main}
  thrown in C:\xampp\htdocs\vendor\symfony\symfony\src\Symfony\Component\Intl\Collator\Collator.php on line 80

Fatal error: Uncaught Symfony\Component\Intl\Exception\MethodArgumentValueNotImplementedException: The Symfony\Component\Intl\Collator\Collator::__construct() method's argument $locale value 'fr_FR' behavior is not implemented. Only the locale "en" is supported.  Please install the "intl" extension for full localization capabilities. in C:\xampp\htdocs\vendor\symfony\symfony\src\Symfony\Component\Intl\Collator\Collator.php:80
Stack trace:
#0 C:\xampp\htdocs\app\SymfonyRequirements.php(619): Symfony\Component\Intl\Collator\Collator->__construct('fr_FR')
#1 C:\xampp\htdocs\app\OroRequirements.php(25): SymfonyRequirements->__construct()
#2 C:\xampp\htdocs\app\DiamanteDeskRequirements.php(16): OroRequirements->__construct()
#3 C:\xampp\htdocs\app\check.php(6): DiamanteDeskRequirements->__construct()
#4 {main}
  thrown in C:\xampp\htdocs\vendor\symfony\symfony\src\Symfony\Component\Intl\Collator\Collator.php on line 80

**Comment by odi-um** [comment]
hi @izakhearn, what version you are using?

**Comment by izakhearn** [comment]
Php7

**Comment by odi-um** [comment]
latest release of DiamanteDesk ? if yes then it is a main issue bc latest release will not work with php7. You should use the unstable version from the master.

**Comment by izakhearn** [comment]
Okay thanks so much
