### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Avnsai** [eltrino/diamantedesk-application#69]
The Installation Stucks at **Clear cache before database initialization**  In Progress...
![screenshot 17](https://user-images.githubusercontent.com/35954216/35560038-3c0c0aa0-05d2-11e8-85df-5bd1bf5667d3.png)

**Comment by northdakota** [comment]
Hi @Avnsai, 
Can you please to provide us logs from file `/app/logsoro_install.log`

Thanks!

**Comment by Avnsai** [comment]
Thankyou For You Reply,
There is No log File in /app

**Comment by northdakota** [comment]
What OS do you use for installation?
Also from what tag or branch you trying to install?

Could you also check please for error messages in browser console
https://github.com/mozilla/thimble.mozilla.org/wiki/Checking-the-browser-console-for-errors

Thanks!

**Comment by Avnsai** [comment]
Ubuntu 16.04,
git clone -b 1.0 https://github.com/eltrino/diamantedesk-application

**Comment by northdakota** [comment]
Thanks for answer, 
Is there are any other log files in `/app/log` directory?

**Comment by Avnsai** [comment]
Solved the problem with simple command
" **chown -R www-data:www-data web app/attachments app/cache app/logs app/config/parameters.yml** "

Thankyou @northdakota (Vladimir Polischuk)  for your help.
