### ISSUE TITLE
Upgrade problem

### ISSUE THREAD

**Issue by xseth** [eltrino/diamantedesk-application#72]
Hi, I can't composer upgrade 
I tryed diagnose and composer self-update is OK but I can't update :/ 

composer update --prefer-dist
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - oro/platform 2.1.x-dev requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.7 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.6 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.5 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.4 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.3 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.2.x-dev requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.2 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.1 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.0 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - oro/platform 2.1.x-dev requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.7 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.6 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.5 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.4 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.3 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.2.x-dev requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.2 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.1 requires php >=7.0 -> your PHP version (5.6.33) does not satisfy that requirement.
    - oro/platform 2.1.0 requires bower-asset/autobahnjs 0.8.0 -> no matching package found.
    - Installation request for oro/platform 2.1.* -> satisfiable by oro/platform[2.1.0, 2.1.1, 2.1.2, 2.1.2.x-dev, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by odi-um** [comment]
@xseth if you are trying to update to master, your system does not meet the main requirement. master have been switched to oroplatform 2.x branch and you should use php 7+ with it.

**Comment by xseth** [comment]
@odi-um thanks for your reply I installed php7 and now I have this error:

> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Oro\Bundle\InstallerBundle\Composer\ScriptHandler::setPermissions
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
PHP Fatal error:  Uncaught Error: Class 'BeSimple\SoapBundle\BeSimpleSoapBundle' not found in /var/www/desk-application/app/cache/dev/bundles.php:20
Stack trace:
#0 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(75): require()
#1 /var/www/desk-application/app/AppKernel.php(29): Oro\Bundle\DistributionBundle\OroKernel->registerBundles()
#2 /var/www/desk-application/app/bootstrap.php.cache(2677): AppKernel->registerBundles()
#3 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(34): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#4 /var/www/desk-application/app/bootstrap.php.cache(2506): Oro\Bundle\DistributionBundle\OroKernel->initializeBundles()
#5 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(252): Symfony\Component\HttpKernel\Kernel->boot()
#6 /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(70): Oro\Bundle\DistributionBu in /var/www/desk-application/app/cache/dev/bundles.php on line 20

**Comment by odi-um** [comment]
@xseth we've just added new version 2.0.4, which solves these issue with outdated dependencies.

**Comment by xseth** [comment]
@odi-um thanks you for new version. I pulled to 2.0.4 
 I have this issue now 

  [Composer\Downloader\TransportException]
  The "https://packagist.orocrm.com/p/oro/platform%2472778c46412b0bbbb6a498734b97c27cd69e1a86c127403ef5e0087212358097.json" file could not be downloaded (HTTP/1.1 404
  Not Found)

**Comment by odi-um** [comment]
do you have any changes in composer.json or composer.lock file? 
could you try to clear composer cache (could be in ~/.composer/cache)?

**Comment by xseth** [comment]
I emptied the composer cache and retry composer update --prefer-dist

And now:

[RuntimeException]
  An error occurred when executing the "'assets:install --symlink '\''web'\'''" command:


  PHP Fatal error:  Uncaught Error: Class 'BeSimple\SoapBundle\BeSimpleSoapBundle' not found in /var/www/desk-application/app/cache/dev/bundles.php:20
  Stack trace:
  #0 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(75): require()
  #1 /var/www/desk-application/app/AppKernel.php(29): Oro\Bundle\DistributionBundle\OroKernel->registerBundles()
  #2 /var/www/desk-application/app/bootstrap.php.cache(2677): AppKernel->registerBundles()
  #3 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(34): Symfony\Component\HttpKernel\Kernel->initializeBundles()
  #4 /var/www/desk-application/app/bootstrap.php.cache(2506): Oro\Bundle\DistributionBundle\OroKernel->initializeBundles()
  #5 /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/DistributionBundle/OroKernel.php(252): Symfony\Component\HttpKernel\Kernel->boot()
  #6 /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(70): Oro\Bundle\DistributionBu in /var/www/desk-applic
  ation/app/cache/dev/bundles.php on line 20

**Comment by odi-um** [comment]
this is bc you have old cache inside app `app/cache/`. it contains the compilation of old files. remove it and rerun composer install.

**Comment by xseth** [comment]
@odi-um Thanks, all assets are successfully installed. Now for run the app
php7.1 app/console oro:platform:update --env=prod --force

I have a runtime error:   [RuntimeException]
  The command '/usr/bin/php7.1' 'app/console' 'oro:migration:load' '--force' '--timeout=300' '--env=prod' terminated with an exit code: 1.

I tryed to change composer timeout to 2000 but I have systematically this error.

**Comment by odi-um** [comment]
@xseth sorry. seems i mixed up issues and confused you a lot.
you were trying to install from master. you should switch back to master and to fix your issue "https://github.com/eltrino/diamantedesk-application/issues/72#issuecomment-365056625" you just needed to clear up `app/cache` folder.

now, regarding timeout issue, try to place 0 instead of some certain number. this will allow you to wait untill it will be finished. at this moment there are no other resolution except to wait till it finished.

**Comment by xseth** [comment]
@odi-um No problem thanks you for your patience, 
I remove app/cache and php7.1 app/console oro:platform:update --env=prod --force --timeout=0
I have this error: 
[RuntimeException]
Failed migrations: Oro\Bundle\ScopeBundle\Migrations\Schema\OroScopeBundleInstaller.

**Comment by odi-um** [comment]
@xseth do you have any other messages? trace maybe?

**Comment by xseth** [comment]
@odi-um yes

Process migrations...
  > Oro\Bundle\EntityExtendBundle\Migration\LoadEntityConfigStateMigration
  > Oro\Bundle\ScopeBundle\Migrations\Schema\OroScopeBundleInstaller
    ERROR: The table with name 'diamantedesk.oro_scope' already exists.
  > Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_5\AddExtendDescription - skipped
  > Oro\Bundle\OrganizationBundle\Migrations\Schema\v1_6\AddScopeRelations - skipped
  > Oro\Bundle\SecurityBundle\Migrations\Schema\v1_1\OroSecurityBundle - skipped
  > Oro\Bundle\SecurityBundle\Migrations\Schema\v1_2\OroSecurityBundle - skipped
  > Oro\Bundle\SecurityBundle\Migrations\Schema\v1_3\UpdateAclEntryFieldNameLength - skipped
  > Oro\Bundle\AttachmentBundle\Migrations\Schema\v1_4\AddOriginalFilenameIndex - skipped
  > Oro\Bundle\AttachmentBundle\Migrations\Schema\v1_5\RenameAttachmentAssociation - skipped
  > Oro\Bundle\OroMessageQueueBundle\Migrations\Schema\OroMessageQueueBundleInstaller - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_19\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_20\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_21\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_22\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_23\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_24\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_25\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_26\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_27\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_28\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_29\OroEmailBundle - skipped
  > Oro\Bundle\EmailBundle\Migrations\Schema\v1_30\OroEmailBundle - skipped
  > Oro\Bundle\CronBundle\Migrations\Schema\v1_3\OroCronBundle - skipped
  > Oro\Bundle\CronBundle\Migrations\Schema\v1_3\RemoveDaemonMonitorSchedule - skipped
  > Oro\Bundle\CronBundle\Migrations\Schema\v2_0\RemoveJmsJob - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_18\ChangeEmailUserFolderRelation - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_18\AddEmailUserColumn - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_18\UpdateEmailUserData - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_18\DropEmailUserColumn - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_19\AddFirstNameLastNameIndex - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_20\OroUserBundle - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_21\AddExtendDescription - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_22\AddImpersonationTable - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_23\AddDisableLogin - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_24\AddImpersonationIpColumn - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_24\AddAuthStatusColumn - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_24\RemoveDisableLogin - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v1_24\AddScopeRelations - skipped
  > Oro\Bundle\UserBundle\Migrations\Schema\v2_0\OroUserBundle - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_1\OroDataGridBundle - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_2\DefaultGridViewUsersRelation - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_3\CreateRelationTable - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_3\FillRelationTable - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_3\DropOldTable - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_4\AddAppearanceType - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_5\UpdateAppearanceTypeIcon - skipped
  > Oro\Bundle\DataGridBundle\Migrations\Schema\v1_5\RemoveAclCapability - skipped
  > Oro\Bundle\TranslationBundle\Migrations\Schema\v1_2\OroTranslationBundle - skipped
  > Oro\Bundle\TranslationBundle\Migrations\Schema\v1_3\OroTranslationBundle - skipped
  > Oro\Bundle\TranslationBundle\Migrations\Schema\v1_3\UpdateTranslationColumns - skipped
  > Oro\Bundle\TranslationBundle\Migrations\Schema\v1_4\OroTranslationBundle - skipped
  > Oro\Bundle\EntityBundle\Migrations\Schema\OroEntityBundleInstaller - skipped
  > Oro\Bundle\LocaleBundle\Migrations\Schema\OroLocaleBundleInstaller - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_7\LoadOptionSets - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_7\MigrateOptionSetsToEnums - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_7\RemoveOptionSetTables - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_8\UpdateConfigFieldForeignKey - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_9\RemoveFieldConfigIndexes - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_10\UpdateConfigFieldDatagridScope - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_11\UpdateEntityConfigData - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_12\OroEntityConfigBundle - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_13\UpdateAclForAttributeFamily - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_13\OroEntityConfigBundle - skipped
  > Oro\Bundle\EntityConfigBundle\Migrations\Schema\v1_14\OroEntityConfigBundle - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_5\FixAssociationLabels - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_6\OroEntityExtendBundle - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_7\FixRestoredFields - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_8\OroEntityExtendBundle - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_9\OroEntityExtendBundle - skipped
  > Oro\Bundle\EntityExtendBundle\Migrations\Schema\v1_10\OroEntityExtendBundle - skipped
  > Oro\Bundle\IntegrationBundle\Migrations\Schema\v1_14\AddPreviouslyEnabled - skipped
  > Oro\Bundle\IntegrationBundle\Migrations\Schema\v1_15\UpdateIntegrationChannelSettingFieldsTypes - skipped
  > Oro\Bundle\ActivityBundle\Migrations\Schema\v1_1\OroActivityBundle - skipped
  > Oro\Bundle\ActivityListBundle\Migrations\Schema\v1_4\OroActivityListBundle - skipped
  > Oro\Bundle\AddressBundle\Migrations\Schema\v1_4\RemoveAclCapability - skipped
  > Oro\Bundle\ConfigBundle\Migrations\Schema\v1_2\OroConfigBundle - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_6\AddColumn - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_6\SetValue - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_6\SetNotNullable - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_7\OroDataAuditBundle - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_8\MakeSomeColumnsNullable - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_8\AddCollectionTypeColumn - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_8\AddUniqueVersionIndex - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_8\AddTransactionIdColumn - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_8\SetTransactionIdNotNullable - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_9\AddImpersonationColumn - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v1_10\OroDataAuditBundle - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_0\DropTemporaryUniqueIndex - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_0\ReplaceNamespaces - skipped
  > Oro\Bundle\DataAuditBundle\Migrations\Schema\v2_0_1\AddIndexToDataAudit - skipped
  > Oro\Bundle\EmbeddedFormBundle\Migrations\Schema\v1_5\AddAllowedDomains - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_4\OroImapBundle - skipped
  > Oro\Bundle\ImapBundle\Migrations\Schema\v1_5\OroImapBundle - skipped
  > Oro\Bundle\ImportExportBundle\Migrations\Schema\OroImportExportBundleInstaller - skipped
  > Oro\Bundle\NoteBundle\Migrations\Schema\v1_2\OroNoteBundle - skipped
  > Oro\Bundle\NoteBundle\Migrations\Schema\v1_3\UpdateNoteAssociationKind - skipped
  > Oro\Bundle\NoteBundle\Migrations\Schema\v1_3\UpdateNoteActivityScopeConfiguration - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\v1_2\AddLogTypeColumn - skipped
  > Oro\Bundle\NotificationBundle\Migrations\Schema\v1_2\AddMassNotificationTable - skipped
  > Oro\Bundle\ReportBundle\Migrations\Schema\v1_5\ReplaceDateTimeFilterPart - skipped
  > Oro\Bundle\ReportBundle\Migrations\Schema\v1_6\OroReportBundle - skipped
  > Oro\Bundle\ReportBundle\Migrations\Schema\v2_0\MigrateRelations - skipped
  > Oro\Bundle\ReportBundle\Migrations\Schema\v2_1\OroReportBundle - skipped
  > Oro\Bundle\SearchBundle\Migrations\Schema\v1_2\RemoveUpdateEntity - skipped
  > Oro\Bundle\SearchBundle\Migrations\Schema\v1_3\OroSearchBundle - skipped
  > Oro\Bundle\SearchBundle\Migrations\Schema\v1_4\UpdateConstraints - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_4\ReplaceDateTimeFilterPart - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_5\OroSegmentBundle - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_6\MigrateRelations - skipped
  > Oro\Bundle\SegmentBundle\Migrations\Schema\v1_7\OroSegmentBundle - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\v1_6\DropAliasColumn - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\v1_6\AddEntityNameRecordIdIndex - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\v1_7\AddTagNameOrganizationIndex - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\v1_8\AddTagTaxonomy - skipped
  > Oro\Bundle\TagBundle\Migrations\Schema\v1_8\RemoveAclCapability - skipped
  > Oro\Bundle\WindowsBundle\Migrations\Schema\v1_1\OroWindowsBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_11\AddPreConditions - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_12\OroWorkflowBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_13\CreateEntityRestrictionsTable - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_14\UpdateWorkflowItemFieldsMigration - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_14\OroWorkflowBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v1_15\OroWorkflowBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v2_0\OroWorkflowBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v2_1\UpdateWorkflowDefinitionConfiguration - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v2_2\AddApplications - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v2_2\OroWorkflowBundle - skipped
  > Oro\Bundle\WorkflowBundle\Migrations\Schema\v2_2_1\UpdateWorkflowConfiguration - skipped
  > Oro\Bundle\CommentBundle\Migrations\Schema\v1_2\RenameCommentAssociation - skipped
  > Oro\Bundle\DashboardBundle\Migrations\Schema\v1_7\OroDashboardBundle - skipped
  > Oro\Bundle\CurrencyBundle\Migrations\Schema\OroConfigBundleInstaller - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_4\OroNavigationBundle - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_5\OroNavigationBundle - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_6\UpdateNavigationMenuUpdIcon - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_6\DropOwnershipFromMenuUpdateTable - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_6\AddScopeToMenuUpdateTable - skipped
  > Oro\Bundle\NavigationBundle\Migrations\Schema\v1_7\DropOroNavigationTitleTable - skipped
  > Oro\Bundle\EntitySerializedFieldsBundle\Migrations\Schema\OroEntitySerializedFieldsBundleInstaller - skipped
  > Oro\Bundle\MigrationBundle\Migration\UpdateBundleVersionMigration
  > Oro\Bundle\NoteBundle\Migration\RemoveNoteConfigurationScopeMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\CleanupTrackingMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\CleanupMarketingListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\CleanupCampaignMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\RefreshExtendCacheMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\UpdateEntityConfigMigration - skipped
  > Oro\Bundle\EntitySerializedFieldsBundle\Migration\SerializedDataMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendConfigMigration - skipped
  > Oro\Bundle\ActivityListBundle\Migration\ActivityListMigration - skipped
  > Oro\Bundle\EntityExtendBundle\Migration\UpdateExtendIndicesMigration - skipped
  > Oro\Bundle\EntityConfigBundle\Migration\WarmUpEntityConfigCacheMigration - skipped


  [RuntimeException]
  Failed migrations: Oro\Bundle\ScopeBundle\Migrations\Schema\OroScopeBundleInstaller.


oro:migration:load [--force] [--dry-run] [--show-queries] [--bundles [BUNDLES]] [--exclude [EXCLUDE]] [--timeout [TIMEOUT]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-s|--shell] [--process-isolation] [-e|--env ENV] [--no-debug] [--current-user CURRENT-USER] [--current-organization CURRENT-ORGANIZATION] [--disabled-listeners DISABLED-LISTENERS] [--] <command>



  [RuntimeException]
  The command '/usr/bin/php7.1' 'app/console' 'oro:migration:load' '--force' '--timeout=0' '--env=prod' terminated with an exit code: 1.


Exception trace:
 () at /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:213
 Oro\Bundle\InstallerBundle\CommandExecutor->processResult() at /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/CommandExecutor.php:156
 Oro\Bundle\InstallerBundle\CommandExecutor->runCommand() at /var/www/desk-application/vendor/oro/platform/src/Oro/Bundle/InstallerBundle/Command/PlatformUpdateCommand.php:70
 Oro\Bundle\InstallerBundle\Command\PlatformUpdateCommand->execute() at /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Component/Console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
 Symfony\Component\Console\Application->doRunCommand() at /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
 Symfony\Component\Console\Application->doRun() at /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:92
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /var/www/desk-application/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:124
 Symfony\Component\Console\Application->run() at /var/www/desk-application/app/console:22

**Comment by odi-um** [comment]
@xseth in case you have data in "diamantedesk.oro_scope" backup it and then remove table. After that cleanup caches and rerun update.

**Comment by xseth** [comment]
@odi-um 
I finally completely reinstall diamantedesk because I've had a lot of tables mistakes in database... 
I run: php7.1 app/console diamante:install --force --drop-database
and php7.1 app/console cache:clear --env prod
Now my diamantedesk work with the new version from branch master. 
Thanks you for your reply and your help
