### ISSUE TITLE
Bower Assets

### ISSUE THREAD

**Issue by rmsferreira** [eltrino/diamantedesk-application#74]
HI all,
Can you please help in this error installing the solution:

 request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/bowerassets/jquery-ajax-queue/ajaxQueue.min.js

I install grump and bower via npm but the bowerassests is note in the folder /web/bundles.

**Comment by odi-um** [comment]
hi @rmsferreira, which version you are trying to install (master or latest stable)?

**Comment by rmsferreira** [comment]
I`m trying to install from branch 2.0

**Comment by odi-um** [comment]
execute following command `composer global require fxp/composer-asset-plugin` and then rerun `composer install`. this will allow composer understand the configuration and fetch all required assets.

**Comment by rmsferreira** [comment]
This works, thanks.
