### ISSUE TITLE
User Entity properties not found

### ISSUE THREAD

**Issue by krasilich** [eltrino/diamantedesk-application#99]
This issue appears from time to time but there are no clear STR.
The most frequent case is when DB out of sync with code.

- Update the code
- Clean the cache
- Run any console command for ex. `bin/console oro:entity-extend:cache:check`

You get one of the following

`Property Oro\Bundle\UserBundle\Entity\User::$avatar does not exist in diama
    nte.ticket.api.service_diamante (which is being imported from "/Users/krasi
    lich/projects/diamantedesk-application/src/Diamante/DeskBundle/Resources/co
    nfig/oro/routing.yml"). Make sure there is a loader supporting the "diamant
    e_rest_service" type.`

`The target-entity Extend\Entity\EV_Auth_Status cannot be found in 'Oro\Bund
    le\UserBundle\Entity\User#auth_status' in diamante.ticket.api.service_diama
    nte (which is being imported from "/Users/krasilich/projects/diamantedesk-a
    pplication/src/Diamante/DeskBundle/Resources/config/oro/routing.yml"). Make
     sure there is a loader supporting the "diamante_rest_service" type.`

**Comment by sylvainraye** [comment]
I know this issue, it’s related to the PHP version you use if I remember well. Which one are you using?

**Comment by linuxprocess** [comment]
Hello,
On a fresh install, I'm encountering the same exception.

My oro version :
```
commit 5d1135300bc20488e7afbe3b167b7950a78107ca (HEAD -> master, origin/master, origin/HEAD)
Merge: b9c8fb82 8f3999a1
Author: CI bot <jenkins-ci@oroinc.com>
Date:   Mon Apr 3 22:00:20 2023 +0000
```

My PHP version is 8.2.2

The Exception :
```
Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("The target-entity Extend\Entity\EV_Auth_Status cannot be found in 'Oro\Bundle\UserBundle\Entity\User#auth_status'.")." at xxx/crm-application/vendor/oro/platform/src/Oro/Bundle/UserBundle/Resources/views/layout.html.twig line 6 
```

If I hack BreadcrumbManager like this :
```
    public function getBreadcrumbLabels($menu, $route)
    {
        $labels = [];
        return $labels;
        $menuItem = $this->getMenuItemByRoute($this->getMenu($menu), $route);
```
I can see the login screen, but when logged in, I meet another exception :
```
Uncaught PHP Exception Doctrine\Persistence\Mapping\MappingException: "Class 'Extend\Entity\EV_Auth_Status' does not exist" at xxx/crm-application/vendor/doctrine/persistence/src/Persistence/Mapping/MappingException.php line 105 
```

Can you precise how to solve ?

Thanks
